from datetime import datetime
from typing import List, Optional
from src.repositories.github import (
    GithubRepo as GhRepo,
    GithubEntity as GhEntity,
    GithubEntityActions as GhEntityActions,
    GithubArchievedStats as GhArchievedStats,
)
from src.models.github import (
    GithubRepo as GithubRepoModel,
    GithubRepoRequest,
    GithubEntity as GithubEntityModel,
    GithubEntityRequest,
    GithubEntityAction as GithubEntityActionModel,
    GithubEntityActionRequest,
    GithubArchievedStat as GithubArchievedStatModel,
    GithubArchievedStatRequest,
)
from src.clients.github import (
    GithubRepoClient,
    GithubEntityClient,
    GithubEntityActionsClient,
    GithubArchievedStatsClient,
)


class GithubRepos:
    def __init__(self, repo: GhRepo, repo_client: GithubRepoClient):
        self.github_repo = repo
        self.repo_client = repo_client

    def get_repo_by_id(self, repo_id: int) -> Optional[GithubRepoModel]:
        return self.github_repo.get_repo_by_id(repo_id)

    def get_repo_by_name(self, name: str) -> List[GithubRepoModel]:
        return self.github_repo.get_repo_by_name(name)

    def create_repo(self, repo_request: GithubRepoRequest, user: str) -> GithubRepoModel:
        complete_repo_model = GithubRepoModel(
            id=0,  # temp placeholder
            record_id="temp",  # might be generated by DB
            name=repo_request.name,
            repo_link=repo_request.repo_link,
            owner=repo_request.owner,
            description=repo_request.description,
            fork=repo_request.fork,
            last_update=repo_request.last_update,
            pushed_at=repo_request.pushed_at,
            archieved=repo_request.archieved,
            license=repo_request.license,
            stargazers_count=repo_request.stargazers_count,
            watchers_count=repo_request.watchers_count,
            forks_count=repo_request.forks_count,
            open_issues_count=repo_request.open_issues_count,
            network_count=repo_request.network_count,
            subscribers_count=repo_request.subscribers_count,
            branches_count=repo_request.branches_count,
            created_at=datetime.now(), 
            created_by=user,
            updated_at=datetime.now(),
            updated_by=user,
            version=1,
        )
        self.github_repo.create_repo(complete_repo_model)
        return complete_repo_model

    def update_repo(self, repo_id: int, updates: dict, user: str) -> Optional[GithubRepoModel]:
        existing_repo = self.github_repo.get_repo_by_id(repo_id)
        if existing_repo is None:
            return None

        # Update only fields provided
        existing_data = existing_repo.model_dump()
        existing_data.update(updates)

        updated_repo = GithubRepoModel(**existing_data)
        updated_repo.updated_at = datetime.now()
        updated_repo.updated_by = user
        updated_repo.version = existing_repo.version + 1

        self.github_repo.update_repo(updated_repo)
        return updated_repo


class GithubEntities:
    def __init__(self, repo: GhEntity, client: GithubEntityClient):
        self.github_entity = repo
        self.entity_client = client

    def get_entity_by_id(self, entity_id: int) -> Optional[GithubEntityModel]:
        return self.github_entity.get_entity_by_id(entity_id)

    def create_entity(self, entity_request: GithubEntityRequest, user: str) -> GithubEntityModel:
        complete_entity_model = GithubEntityModel(
            id=0,
            name=entity_request.name,
            user_id=entity_request.user_id,
            company=entity_request.company,
            email=entity_request.email,
            location=entity_request.location,
            type=entity_request.type,
            created_at=datetime.now(),
            created_by=user,
            updated_at=datetime.now(),
            updated_by=user,
            version=1,
        )
        self.github_entity.create_entity(complete_entity_model)
        return complete_entity_model


class GithubEntityActions:
    def __init__(self, repo: GhEntityActions, client: GithubEntityActionsClient):
        self.github_entity_actions = repo
        self.actions_client = client

    def create_action(self, action_request: GithubEntityActionRequest, user: str) -> GithubEntityActionModel:
        complete_action_model = GithubEntityActionModel(
            id=0,
            repo_id=action_request.repo_id,
            action_type=action_request.action_type,
            user_id=action_request.user_id,
            created_at=datetime.now(),
            created_by=user,
            updated_at=datetime.now(),
            updated_by=user,
            version=1,
        )
        self.github_entity_actions.create_action(complete_action_model)
        return complete_action_model


class GithubArchievedStats:
    def __init__(self, repo: GhArchievedStats, client: GithubArchievedStatsClient):
        self.github_archieved_stats = repo
        self.stats_client = client

    def create_stats(self, stats_request: GithubArchievedStatRequest, user: str) -> GithubArchievedStatModel:
        complete_stats_model = GithubArchievedStatModel(
            id=0,
            repo_id=stats_request.repo_id,
            weekly_commit_add=stats_request.weekly_commit_add,
            weekly_commit_del=stats_request.weekly_commit_del,
            yearly_commit_count=stats_request.yearly_commit_count,
            daily_clone_count=stats_request.daily_clone_count,
            daily_view_count=stats_request.daily_view_count,
            last_14_day_top_referral_sources=stats_request.last_14_day_top_referral_sources,
            last_14_day_top_referral_path=stats_request.last_14_day_top_referral_path,
            created_at=datetime.now(),
            created_by=user,
            updated_at=datetime.now(),
            updated_by=user,
            version=1,
        )
        self.github_archieved_stats.create_stats(complete_stats_model)
        return complete_stats_model
