blank_issues_enabled: false
contact_links:
  - name: 🐞 Bug Report
    url: https://github.com/ga4gh/analytics-dashboard/new/main/.github/ISSUE_TEMPLATE/bug.yml
    about: Please file a bug/issue report.
