DROP TRIGGER IF EXISTS trg_audit_github_repos ON public.github_repos;
DROP FUNCTION IF EXISTS github_repos_audit_trigger_func;
DROP TABLE IF EXISTS github_repos_audit;
DROP INDEX IF EXISTS idx_github_repos_audit_repo_id;
DROP INDEX IF EXISTS idx_github_repos_audit_action_tstamp;
DROP INDEX IF EXISTS idx_github_repos_record_id;
DROP INDEX IF EXISTS idx_github_repos_owner;
DROP INDEX IF EXISTS idx_github_repos_is_archived;
DROP INDEX IF EXISTS idx_github_repos_license;
DROP INDEX IF EXISTS idx_github_repos_last_updated;
DROP INDEX IF EXISTS idx_github_repos_pushed_at;
DROP TABLE IF EXISTS github_repos;
