DROP TRIGGER IF EXISTS trg_audit_authors ON public.authors;
DROP FUNCTION IF EXISTS authors_audit_trigger_func;
DROP TABLE IF EXISTS authors_audit;
DROP INDEX IF EXISTS idx_authors_audit_authors_id;
DROP INDEX IF EXISTS idx_authors_audit_action_tstamp;
DROP INDEX IF EXISTS idx_authors_article_id;
DROP INDEX IF EXISTS idx_authors_article_type;
DROP INDEX IF EXISTS idx_authors_is_primary;
DROP INDEX IF EXISTS idx_authors_deleted_at;
DROP TABLE IF EXISTS authors;
