DROP TRIGGER IF EXISTS trg_audit_articles ON public.articles;
DROP FUNCTION IF EXISTS articles_audit_trigger_func;
DROP TABLE IF EXISTS articles_audit;
DROP INDEX IF EXISTS idx_articles_record_id;
DROP INDEX IF EXISTS idx_articles_source_id;
DROP INDEX IF EXISTS idx_articles_status;
DROP INDEX IF EXISTS idx_articles_publish_date;
DROP INDEX IF EXISTS idx_articles_deleted_at;
DROP INDEX IF EXISTS idx_articles_audit_articles_id;
DROP INDEX IF EXISTS idx_articles_audit_action_tstamp;
DROP TABLE IF EXISTS articles;
